import { type NextPage } from "next";
import Head from "next/head";

const BackgroundsShadows: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="p-10">
        {/* Background classes */}
        <div
          className="h-64 w-72 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: "url('/img1.jpg')" }}
        ></div>
        {/* Gradients */}
        <div className="h-24 bg-gradient-to-r from-cyan-500 to-blue-500"></div>
        <div className="h-24 bg-gradient-to-l from-cyan-500 to-blue-500"></div>
        {/* Shadows */}
        <div className="mt-6 ml-4 w-96 p-3 shadow">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-md">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-lg">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-xl">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-2xl">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-inner">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-2xl shadow-blue-500/50">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>
        <div className="mt-6 ml-4 w-96 p-3 shadow-2xl shadow-red-500">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          accusamus recusandae voluptatum corrupti voluptates officiis itaque?
          Sequi quam quaerat facilis itaque quasi labore, deserunt fugiat.
        </div>

        {/* Mix Blend */}
        <div className="mt-10 flex justify-center -space-x-24">
          <div className="bg-blue-400 mix-blend-multiply">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt
            possimus totam necessitatibus.
          </div>
          <div className="bg-pink-400 mix-blend-multiply">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore
            impedit obcaecati nisi.
          </div>
        </div>
      </main>
    </>
  );
};

export default BackgroundsShadows;
