import { type NextPage } from "next";
import Head from "next/head";

const Colors: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="p-10">
        {/* Text Colors */}
        <p className="text-black">Tailwind is awesome</p>
        <p className="bg-black text-white">Tailwind is awesome</p>
        <p className="text-red-500">Tailwind is awesome</p>
        <p className="text-green-600">Tailwind is awesome</p>
        <p className="text-emerald-400">Tailwind is awesome</p>
        <p className="text-zinc-200">Tailwind is awesome</p>
        <p className="text-slate-300">Tailwind is awesome</p>

        {/* Background Colors */}
        <p className="bg-slate-900 text-white ">Tailwind is awesome</p>
        <p className="bg-emerald-400">Tailwind is awesome</p>
        <p className="bg-yellow-600">Tailwind is awesome</p>
        <p className="bg-indigo-800">Tailwind is awesome</p>

        {/* Text Underline */}
        <p className="underline decoration-red-500 ">Tailwind is awesome</p>
        <p className="underline decoration-emerald-600 ">Tailwind is awesome</p>
        <p className="underline decoration-yellow-800 ">Tailwind is awesome</p>

        {/* Border Color */}
        <p className="border border-blue-400">Tailwind is awesome</p>
        <p className="border border-green-800">Tailwind is awesome</p>
        <p className="border border-orange-600">Tailwind is awesome</p>

        {/* Divide Color */}
        <div className="divide-y divide-blue-300">
          <div>Item 1</div>
          <div>Item 2</div>
          <div>Item 3</div>
          <div>Item 4</div>
          <div>Item 5</div>
        </div>

        {/* Outline Color */}
        <button className="outline outline-red-500">Hello</button>
        <button className="outline outline-blue-200">Hello</button>

        {/* Box Shadow Colors */}
        <div className="bg-cyan-500 shadow-lg shadow-cyan-500">Subscribe</div>
        <div className="bg-cyan-500 shadow-lg shadow-cyan-500/60">
          Subscribe
        </div>

        {/* Accent Colors */}
        <input type="checkbox" className="accent-purple-500" checked />
        <input type="checkbox" className="accent-cyan-800" checked />

        {/* Arbitrary Colors */}
        <div className="bg-[#427fab]">Hello</div>
        <div className="bg-[rgb(255,0,0)]">Hello</div>
        <div className="bg-[steelBlue]">Hello</div>
      </main>
    </>
  );
};

export default Colors;
