import { type NextPage } from "next";
import Head from "next/head";

const ContainerSpacing: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="p-10">
        <div className="container mx-auto">
          <article>
            <h3>Article One</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil
              repellat, deleniti assumenda excepturi numquam facilis doloremque
              et nostrum ut reprehenderit iusto aliquid atque quas, officia
              sequi autem, tempora totam. Reprehenderit!
            </p>
          </article>
        </div>

        {/* Margin */}
        <div className="m-2 bg-slate-200">Hello World</div>
        <div className="ml-2 bg-slate-200">Hello World</div>
        <div className="mr-2 bg-slate-200">Hello World</div>
        <div className="mt-2 bg-slate-200">Hello World</div>
        <div className="mb-2 bg-slate-200">Hello World</div>
        <div className="m-[20px] bg-slate-200">Hello World</div>

        {/* Padding */}
        <div className="bg-slate-200 p-2">Hello World</div>
        <div className="bg-slate-200 pl-2">Hello World</div>
        <div className="bg-slate-200 pr-2">Hello World</div>
        <div className="bg-slate-200 pt-2">Hello World</div>
        <div className="bg-slate-200 pb-2">Hello World</div>
        <div className="bg-slate-200 p-[20px]">Hello World</div>

        {/* Space Between X */}
        <div className="mt-5 flex space-x-4">
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
        </div>

        {/* Space Between Y */}
        <div className="mt-5 flex flex-col space-y-4">
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
          <div>Item 5</div>
        </div>
      </main>
    </>
  );
};

export default ContainerSpacing;
