import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Interactivity: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="p-10">
        <div className="grid grid-cols-3 ">
          <div className="bg-bluee-100 col-span-3 row-span-3 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 col-span-3 border border-blue-600 p-10"></div>
          <div className="bg-bluee-100 border border-blue-600 p-10"></div>
        </div>
      </main>
    </>
  );
};

export default Interactivity;
