import { type NextPage } from "next";
import Head from "next/head";

const Interactivity: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="flex flex-col gap-10  p-10">
        {/* Hover state Styling */}
        <button className="rounded-lg bg-black py-3 px-5 text-white hover:bg-orange-400 hover:text-blue-500">
          Hover
        </button>
        {/* Focus state Styling */}
        <button className="rounded-lg bg-black py-3 px-5 text-white focus:bg-orange-400 focus:text-blue-500">
          Focus
        </button>
        {/* Active state Styling */}
        <button className="rounded-lg bg-black py-3 px-5 text-white active:bg-orange-400 active:text-blue-500">
          Active
        </button>
        {/* Styling based on parent state */}
        <a
          href=""
          className="max-auto group block max-w-xs space-y-3 rounded-lg bg-white p-6 shadow-lg hover:bg-sky-500"
        >
          <h3 className="group-hover:text-white">Card Title</h3>
          <p className="group-hover:text-white">This is a group example</p>
        </a>
        {/* Pseudo Classes */}
        <ul>
          <li className="odd:bg-yellow-400 even:bg-green-600">item 1</li>
          <li className="odd:bg-yellow-400 even:bg-green-600">item 2</li>
          <li className="odd:bg-yellow-400 even:bg-green-600">item 3</li>
          <li className="odd:bg-yellow-400 even:bg-green-600">item 4</li>
          <li className="odd:bg-yellow-400 even:bg-green-600">item 5</li>
        </ul>
        <ul>
          <li className="first:bg-red-400 ">item 1</li>
          <li className="first:bg-red-400 ">item 2</li>
          <li className="first:bg-red-400 ">item 3</li>
          <li className="first:bg-red-400 ">item 4</li>
          <li className="first:bg-red-400 ">item 5</li>
        </ul>
        {/* Appearance */}
        <select name="" id="" className="appearance-none">
          <option value="yes">Yes</option>
          <option value="no">No</option>
        </select>
        {/* Cursor */}
        <button className="cursor-wait rounded-lg bg-black py-3 px-5 text-white ">
          Wait
        </button>
        <button className="cursor-not-allowed rounded-lg bg-black py-3 px-5 text-white ">
          Wait
        </button>
        <p className="cursor-pointer">This is a pointer</p>
        {/* User select */}
        <div className="select-none">Lorem ipsum dolor sit amet.</div>
        <div className="select-text">Lorem ipsum dolor sit amet.</div>
        <div className="select-all">Lorem ipsum dolor sit amet.</div>
        <div className="select-auto">Lorem ipsum dolor sit amet.</div>

        {/* Smooth Scrolling */}
        <a href="#item" className="my-6 block scroll-smooth">
          Go to item
        </a>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut ipsum
          fugit quam quas assumenda. Autem debitis soluta dicta ipsa placeat.
          Totam, officia ex quasi id suscipit reiciendis magni necessitatibus
          labore sunt autem, nostrum est quisquam molestias, laudantium
          obcaecati. Placeat incidunt ad omnis doloribus quo dolor odit
          aspernatur rerum dicta ipsum cum voluptatum, repudiandae eos
          necessitatibus saepe tenetur beatae maxime corrupti! Laboriosam,
          molestias itaque molestiae omnis esse accusamus architecto beatae
          distinctio corporis laudantium, dicta libero sint in autem id quas ad
          saepe explicabo. Magni architecto recusandae quidem culpa sit sed
          numquam. Quas ad iure minus porro eos dolore quidem labore, expedita,
          adipisci, magnam ea dignissimos incidunt explicabo laborum eaque
          minima unde voluptatem corporis aspernatur officiis atque fuga
          delectus. Praesentium fugiat, dolor voluptatem nemo architecto,
          voluptate, neque qui nam mollitia sit optio culpa voluptatibus ipsum
          impedit autem iure recusandae fugit molestiae dolorem! Hic neque
          dicta, officiis sequi esse perferendis nulla, ratione eum autem soluta
          consequuntur a placeat expedita error quisquam libero, magni voluptate
          odio consectetur molestiae! A, maxime eum ipsa laborum quasi nihil
          consequatur magnam ducimus mollitia obcaecati minima quam incidunt id
          explicabo, perferendis excepturi optio sapiente accusantium voluptate
          nobis, adipisci corrupti est. Quos saepe et officia, beatae sint
          ullam, aperiam, quia placeat deserunt commodi voluptatibus ad suscipit
          quas voluptatum ex. Quae quis quas aperiam earum eligendi voluptate
          laborum numquam ad. Magni, et. Tempore ratione doloremque obcaecati a
          harum quaerat itaque aliquid unde est suscipit, reprehenderit ullam,
          sequi nostrum cum iure nemo tenetur aut. Similique odio ab nesciunt
          sequi praesentium illo harum voluptate asperiores cumque ad laudantium
          nobis inventore ut, quis molestias maiores saepe exercitationem
          placeat totam officiis! Voluptate, officia aliquam quis voluptatem
          tempore a aut minima temporibus, eveniet ex, tenetur porro quas.
          Deleniti quaerat voluptatem recusandae dolorem harum, debitis
          molestias? Architecto autem ratione corporis omnis eligendi corrupti,
          consequuntur laudantium minima voluptates. Quod, in. Corporis beatae
          laborum, perspiciatis iste debitis earum odio quidem error aspernatur
          minima consectetur ipsam veritatis ullam eaque libero saepe! Ut ex
          voluptatibus esse dolor numquam aliquid officiis odio voluptate? Qui
          porro repellat ad a perspiciatis, officia omnis quasi, fuga ducimus
          quod nemo ipsam nostrum eaque sed fugit deserunt quia, tempore atque
          culpa. In quaerat dolor accusamus fugiat. Perferendis culpa pariatur
          ipsam, fugit officia placeat error, esse possimus delectus dicta natus
          temporibus nostrum! Impedit aliquid rem delectus dignissimos placeat
          ipsa assumenda quo. Blanditiis voluptate dolores culpa tempore velit
          obcaecati, nemo architecto labore debitis neque dolorum magnam illum
          dignissimos aut?
        </p>
        <div id="item">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur
          accusamus, odit blanditiis debitis quidem aut doloremque libero quo
          animi adipisci vero magnam facilis, quibusdam officiis ratione harum
          itaque sit. Laboriosam, vel tempora iure mollitia, reiciendis
          voluptatum eligendi labore vero in ullam debitis doloremque eaque
          ratione nisi laudantium voluptatibus sint facere.
        </div>
      </main>
    </>
  );
};

export default Interactivity;
