import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Interactivity: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/tailwind-icon.png" />
      </Head>
      <main className="p-10"></main>
    </>
  );
};

export default Interactivity;
