import { type NextPage } from "next";
import Head from "next/head";

const Typography: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10">
        {/* Font Family */}
        <div className="font-sans">Tailwind is awesome</div>
        <div className="font-serif">Tailwind is awesome</div>
        <div className="font-mono">Tailwind is awesome</div>

        {/* Font Size */}
        <div className="text-xs">Tailwind is awesome</div>
        <div className="text-sm">Tailwind is awesome</div>
        <div className="text-base">Tailwind is awesome</div>
        <div className="text-lg">Tailwind is awesome</div>
        <div className="text-xl">Tailwind is awesome</div>
        <div className="text-2xl">Tailwind is awesome</div>

        {/* Font Weight */}
        <div className="font-thin">Tailwind is awesome</div>
        <div className="font-extralight">Tailwind is awesome</div>
        <div className="font-light">Tailwind is awesome</div>
        <div className="font-normal">Tailwind is awesome</div>
        <div className="font-medium">Tailwind is awesome</div>
        <div className="font-semibold">Tailwind is awesome</div>
        <div className="font-bold">Tailwind is awesome</div>

        {/* Letter spacing */}
        <div className="tracking-tighter">Tailwind is awesome</div>
        <div className="tracking-tight">Tailwind is awesome</div>
        <div className="tracking-normal">Tailwind is awesome</div>
      </main>
    </>
  );
};

export default Typography;
