import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const UtilityFirst: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10">
        <div className="mx-auto mt-12 flex max-w-lg items-center space-x-4 rounded-xl bg-white p-6 shadow-lg">
          <Image src="/warning.svg" alt="warning sign" width={64} height={64} />
          <div>
            <div className="text-xl font-medium text-black">Are you sure?</div>
            <p className="text-slate-500">You are about to delete a post</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default UtilityFirst;
